### ISSUE TITLE
Add a CONTRIBUTING file

### ISSUE THREAD

**Issue by ryzokuken** [publiclab/plotsbot#31] opened 2017-06-11 17:19 UTC
Add a CONTRIBUTING markdown file, shift the current contribution information from the README to this file, add information about how to name branches and everything, general guidelines regarding contributing to the project. Also, this file would be the most appropriate place to include the content to be added under #11.

Link this file to the README.

**Comment by ryzokuken** [comment] 2017-06-16 17:35
@jywarren what do you think about this one?

**Comment by jywarren** [comment] 2017-06-16 20:03
Well, I think the README can be quite long before this is needed, and it's great for it to be all in one place. So maybe we could wait on this until the README gets really really long?

**Comment by ryzokuken** [comment] 2017-06-17 05:19
@jywarren sure, sounds good.

**Comment by amitsin6h** [comment] 2018-02-18 08:20
@jywarren @ryzokuken can I work on this as my first contribution to PublicLab

**Comment by ryzokuken** [comment] 2018-02-18 08:45
Sure! Please feel free to go ahead.

**Comment by amitsin6h** [comment] 2018-02-18 08:49
@ryzokuken what I understand from the issue is that we need to create a CONTRIBUTING .md file. but what things I have to write in the file.

**Comment by ryzokuken** [comment] 2018-02-18 11:40
Try looking at a few CONTRIBUTING.md files, especially the one we use at plots2. We'd basically need resources for new contributors in there. Make a PR with a dummy file and we could discuss the specifics inside that PR.

Thanks.

**Comment by amitsin6h** [comment] 2018-02-18 12:25
@ryzokuken could you please the PR #94

**Comment by gauravano** [comment] 2019-02-02 22:59
@ryzokuken @jywarren can I close this one as #94 seems to solve this issue? Thanks!

**Closed** 2019-02-04 18:06 UTC
Labels: documentation, enhancement, fto-candidate, help wanted
